name: Chrome Canyon
favicon: null
layout_spectrum: 0.20614
typography_spectrum: 0.4055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#8c5c4d'
    - '#ca9372'
    - '#8523e6'
  brandStrength: 0
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
